<?php

namespace Database\Seeders;

use App\Models\ClientAccount;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ClientAccountSeeder extends Seeder
{
    public const CLIENT_DIRECTORY = [
        [
            'company_id' => 'CLT-2026-0001',
            'company' => 'ABC Logistics',
            'industry' => 'Warehousing & Logistics',
            'status' => 'active',
            'am' => 'Karla Reyes',
            'contract' => 'Staffing (Contingency)',
            'renewal' => 'Sep 30, 2026',
            'rate' => '₱185/hr avg',
            'card_icon' => 'box',
            'card_tag' => 'Warehousing · Logistics',
            'card_blurb' => 'Filling 15 warehouse and forklift roles for the Q3 volume surge.',
            'revenue_q' => '₱1.2M',
            'tenure' => '1y 6m',
            'next_event' => 'Contract renewal call · Sep 30',
            'contact_person' => 'Ricardo M. Santos',
            'designation' => 'HR Manager',
            'email' => 'hr@abclogistics.com.ph',
            'mobile' => '+63 917 555 0101',
            'password' => 'BCL@2026',
            'sites' => [
                ['name' => 'Valenzuela DC', 'location' => 'Valenzuela City, NCR', 'activeHeadcount' => 22],
                ['name' => 'Calamba Hub', 'location' => 'Calamba, Laguna', 'activeHeadcount' => 10],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0002',
            'company' => 'Northline BPO',
            'industry' => 'Business Process Outsourcing',
            'status' => 'active',
            'am' => 'Dennis Ocampo',
            'contract' => 'Direct Hire SLA',
            'renewal' => 'Dec 31, 2026',
            'rate' => '₱240/hr avg',
            'card_icon' => 'headset',
            'card_tag' => 'BPO · Customer Experience',
            'card_blurb' => 'Ongoing recruitment for CSR, TSR, and bilingual voice accounts.',
            'revenue_q' => '₱2.1M',
            'tenure' => '2y 1m',
            'next_event' => 'Quarterly QBR · Oct 15',
            'contact_person' => 'Carmela R. Tan',
            'designation' => 'Talent Acquisition Lead',
            'email' => 'talent@northlinebpo.com.ph',
            'mobile' => '+63 918 555 0202',
            'password' => 'NRT@2026',
            'sites' => [
                ['name' => 'BGC Tower 1', 'location' => 'Taguig City, NCR', 'activeHeadcount' => 35],
                ['name' => 'Cebu IT Park', 'location' => 'Cebu City', 'activeHeadcount' => 18],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0003',
            'company' => 'Delta Manufacturing',
            'industry' => 'Manufacturing',
            'status' => 'active',
            'am' => 'Karla Reyes',
            'contract' => 'Staffing (Fixed-term)',
            'renewal' => 'Aug 31, 2026',
            'rate' => '₱160/hr avg',
            'card_icon' => 'gear',
            'card_tag' => 'Manufacturing · Industrial',
            'card_blurb' => 'Supplying 20 machine operators and QA staff for Plant 3 expansion.',
            'revenue_q' => '₱980k',
            'tenure' => '11m',
            'next_event' => 'Contract extension review · Aug 15',
            'contact_person' => 'Edwin G. Pascual',
            'designation' => 'Plant HR Officer',
            'email' => 'hr@deltamfg.com.ph',
            'mobile' => '+63 919 555 0303',
            'password' => 'DLT@2026',
            'sites' => [
                ['name' => 'Plant 1', 'location' => 'Canlubang, Laguna', 'activeHeadcount' => 28],
                ['name' => 'Plant 3', 'location' => 'Carmona, Cavite', 'activeHeadcount' => 14],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0004',
            'company' => 'Coastal Retail Group',
            'industry' => 'Retail',
            'status' => 'active',
            'am' => 'Dennis Ocampo',
            'contract' => 'Staffing (Seasonal)',
            'renewal' => 'Oct 31, 2026',
            'rate' => '₱150/hr avg',
            'card_icon' => 'cart',
            'card_tag' => 'Retail · Consumer Goods',
            'card_blurb' => 'Sourcing cashiers, sales associates, and stock clerks for 8 mall branches.',
            'revenue_q' => '₱750k',
            'tenure' => '8m',
            'next_event' => 'Holiday ramp-up planning · Sep 1',
            'contact_person' => 'Juanita M. Dela Cruz',
            'designation' => 'Human Resources Manager',
            'email' => 'hr@coastalretail.com.ph',
            'mobile' => '+63 917 555 0404',
            'password' => 'CST@2026',
            'sites' => [
                ['name' => 'Mall of Asia Branch', 'location' => 'Pasay City, NCR', 'activeHeadcount' => 12],
                ['name' => 'Megamall Branch', 'location' => 'Mandaluyong City, NCR', 'activeHeadcount' => 10],
                ['name' => 'North EDSA Branch', 'location' => 'Quezon City, NCR', 'activeHeadcount' => 14],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0005',
            'company' => 'Vantage Tech Solutions',
            'industry' => 'Information Technology',
            'status' => 'prospect',
            'am' => 'Karla Reyes',
            'contract' => 'Not yet signed',
            'renewal' => '—',
            'rate' => 'TBD',
            'card_icon' => 'spark',
            'card_tag' => 'Information Technology',
            'card_blurb' => 'Proposal sent, awaiting sign-off on staffing terms.',
            'revenue_q' => '—',
            'tenure' => 'New',
            'next_event' => 'Follow-up call · This week',
            'contact_person' => 'Patrick L. Chua',
            'designation' => 'VP of Operations',
            'email' => 'ops@vantagetech.com.ph',
            'mobile' => '+63 920 555 0505',
            'password' => 'VNT@2026',
            'sites' => [],
        ],
        [
            'company_id' => 'CLT-2026-0006',
            'company' => 'Everwell Health Group',
            'industry' => 'Healthcare',
            'status' => 'prospect',
            'am' => 'Dennis Ocampo',
            'contract' => 'Not yet signed',
            'renewal' => '—',
            'rate' => 'TBD',
            'card_icon' => 'heart',
            'card_tag' => 'Healthcare · Wellness',
            'card_blurb' => 'NDA pending before rate and volume discussion begins.',
            'revenue_q' => '—',
            'tenure' => 'New',
            'next_event' => 'NDA signature · Pending',
            'contact_person' => 'Dr. Lilian A. Reyes',
            'designation' => 'Chief Medical Officer',
            'email' => 'admin@everwellhealth.com.ph',
            'mobile' => '+63 921 555 0606',
            'password' => 'VRW@2026',
            'sites' => [],
        ],
        [
            'company_id' => 'CLT-2026-0007',
            'company' => 'Ironclad Freight Co.',
            'industry' => 'Freight & Transport',
            'status' => 'inactive',
            'am' => 'Dennis Ocampo',
            'contract' => 'Expired Jun 30, 2026',
            'renewal' => 'Jun 30, 2026',
            'rate' => '₱175/hr avg',
            'card_icon' => 'truck',
            'card_tag' => 'Freight · Logistics',
            'card_blurb' => 'Contract expired last month; re-engagement outreach sent.',
            'revenue_q' => '₱0',
            'tenure' => '1y 0m',
            'next_event' => 'Re-engagement outreach sent',
            'contact_person' => 'Manuel B. Reyes',
            'designation' => 'Operations Manager',
            'email' => 'ops@ironcladfreight.com.ph',
            'mobile' => '+63 922 555 0707',
            'password' => 'RNC@2026',
            'sites' => [],
        ],
        [
            'company_id' => 'CLT-2026-0008',
            'company' => 'Sunrise Hospitality Group',
            'industry' => 'Hospitality & Leisure',
            'status' => 'active',
            'am' => 'Karla Reyes',
            'contract' => 'Staffing (Contingency)',
            'renewal' => 'Nov 15, 2026',
            'rate' => '₱195/hr avg',
            'card_icon' => 'coffee',
            'card_tag' => 'Hospitality · Leisure',
            'card_blurb' => 'Fulfilling 15 seasonal resort staff positions for the holiday rush.',
            'revenue_q' => '₱850k',
            'tenure' => '1y 2m',
            'next_event' => 'Mid-year review · Aug 10',
            'contact_person' => 'Maria Teresa C. Lopez',
            'designation' => 'HR Director',
            'email' => 'hr@sunrisehospitality.com.ph',
            'mobile' => '+63 923 555 0808',
            'password' => 'SNR@2026',
            'sites' => [
                ['name' => 'Boracay Grand Resort', 'location' => 'Boracay, Aklan', 'activeHeadcount' => 16],
                ['name' => 'Cebu Beach Club', 'location' => 'Lapu-Lapu City, Cebu', 'activeHeadcount' => 12],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0009',
            'company' => 'Prime Realty Corp',
            'industry' => 'Real Estate & Property Management',
            'status' => 'active',
            'am' => 'Dennis Ocampo',
            'contract' => 'Managed Services SLA',
            'renewal' => 'Dec 15, 2026',
            'rate' => '₱210/hr avg',
            'card_icon' => 'building',
            'card_tag' => 'Real Estate · Facility Ops',
            'card_blurb' => 'Deploying leasing officers, maintenance techs, and front desk personnel.',
            'revenue_q' => '₱1.1M',
            'tenure' => '1y 4m',
            'next_event' => 'Building safety audit · Aug 20',
            'contact_person' => 'Atty. Ronaldo F. Bautista',
            'designation' => 'Head of Property Management',
            'email' => 'hr@primerealty.com.ph',
            'mobile' => '+63 924 555 0909',
            'password' => 'PRM@2026',
            'sites' => [
                ['name' => 'Prime Tower Ortigas', 'location' => 'Pasig City, NCR', 'activeHeadcount' => 18],
                ['name' => 'Prime Heights BGC', 'location' => 'Taguig City, NCR', 'activeHeadcount' => 14],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0010',
            'company' => 'Metro Health Diagnostics',
            'industry' => 'Healthcare & Diagnostics',
            'status' => 'active',
            'am' => 'Karla Reyes',
            'contract' => 'Direct Hire SLA',
            'renewal' => 'Jan 15, 2027',
            'rate' => '₱230/hr avg',
            'card_icon' => 'heart',
            'card_tag' => 'Healthcare · Diagnostics',
            'card_blurb' => 'Staffing licensed medical technologists and radiologic techs for 6 clinic branches.',
            'revenue_q' => '₱1.3M',
            'tenure' => '1y 1m',
            'next_event' => 'DOH compliance check · Aug 25',
            'contact_person' => 'Dr. Sofia G. Mercado',
            'designation' => 'Branch Operations Head',
            'email' => 'hr@metrohealthdiag.com.ph',
            'mobile' => '+63 925 555 1010',
            'password' => 'MTR@2026',
            'sites' => [
                ['name' => 'Quezon Ave Main', 'location' => 'Quezon City, NCR', 'activeHeadcount' => 15],
                ['name' => 'Manila Clinic Hub', 'location' => 'Ermita, Manila', 'activeHeadcount' => 11],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0011',
            'company' => 'Apex Construction Builders',
            'industry' => 'Construction & Engineering',
            'status' => 'active',
            'am' => 'Karla Reyes',
            'contract' => 'Project-based Staffing',
            'renewal' => 'Jan 30, 2027',
            'rate' => '₱220/hr avg',
            'card_icon' => 'gear',
            'card_tag' => 'Construction · Heavy Infra',
            'card_blurb' => 'Providing 30 certified operators and skilled trades for QC high-rise project.',
            'revenue_q' => '₱1.4M',
            'tenure' => '1y 8m',
            'next_event' => 'Safety compliance review · Aug 1',
            'contact_person' => 'Engr. Roberto S. Mendoza',
            'designation' => 'Project Director',
            'email' => 'hr@apexbuilders.com.ph',
            'mobile' => '+63 927 555 1212',
            'password' => 'PXC@2026',
            'sites' => [
                ['name' => 'SkyRise Tower QC Site', 'location' => 'Quezon City, NCR', 'activeHeadcount' => 38],
                ['name' => 'Bayfront Reclamation Site', 'location' => 'Pasay City, NCR', 'activeHeadcount' => 24],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0012',
            'company' => 'GreenFields Agri Export',
            'industry' => 'Agriculture & Export',
            'status' => 'active',
            'am' => 'Dennis Ocampo',
            'contract' => 'Staffing (Seasonal)',
            'renewal' => 'Feb 28, 2027',
            'rate' => '₱165/hr avg',
            'card_icon' => 'box',
            'card_tag' => 'Agriculture · Export',
            'card_blurb' => 'Recruiting 40 packing and sorting personnel for harvest season.',
            'revenue_q' => '₱1.0M',
            'tenure' => '9m',
            'next_event' => 'Harvest logistics briefing · Sep 5',
            'contact_person' => 'Engr. Carlos P. Villanueva',
            'designation' => 'Plant Manager',
            'email' => 'operations@greenfieldsagri.com.ph',
            'mobile' => '+63 926 555 1111',
            'password' => 'GRN@2026',
            'sites' => [
                ['name' => 'Batangas Processing Hub', 'location' => 'Lipa City, Batangas', 'activeHeadcount' => 25],
                ['name' => 'Davao Cold Chain Facility', 'location' => 'Davao City', 'activeHeadcount' => 15],
            ],
        ],
        [
            'company_id' => 'CLT-2026-0013',
            'company' => 'Nordic Freight Co.',
            'industry' => 'Freight & Transport',
            'status' => 'prospect',
            'am' => 'Karla Reyes',
            'contract' => 'Not yet signed',
            'renewal' => '—',
            'rate' => 'TBD',
            'card_icon' => 'truck',
            'card_tag' => 'Freight · Logistics',
            'card_blurb' => 'Contract proposal under review for bonded warehouse staffing.',
            'revenue_q' => '—',
            'tenure' => 'New',
            'next_event' => 'Proposal review · Next week',
            'contact_person' => 'Alfredo T. Navarro',
            'designation' => 'Fleet Operations Head',
            'email' => 'ops@nordicfreight.com.ph',
            'mobile' => '+63 928 555 1313',
            'password' => 'NRD@2026',
            'sites' => [],
        ],
        [
            'company_id' => 'CLT-2026-0014',
            'company' => 'Coastline Retail Group',
            'industry' => 'Retail',
            'status' => 'prospect',
            'am' => 'Dennis Ocampo',
            'contract' => 'Not yet signed',
            'renewal' => '—',
            'rate' => 'TBD',
            'card_icon' => 'bag',
            'card_tag' => 'Retail · Store Ops',
            'card_blurb' => 'Sister brand of Coastal Retail exploring seasonal promo merchandisers.',
            'revenue_q' => '—',
            'tenure' => 'New',
            'next_event' => 'Initial discovery call · Pending',
            'contact_person' => 'Jasmine D. Uy',
            'designation' => 'Former HR Head',
            'email' => 'hr@coastlineretail.com.ph',
            'mobile' => '+63 929 555 1414',
            'password' => 'CST@2026',
            'sites' => [],
        ],
    ];

    public function run(): void
    {
        foreach (self::CLIENT_DIRECTORY as $clientData) {
            ClientAccount::updateOrCreate(
                ['email' => $clientData['email']],
                [
                    'company_id' => $clientData['company_id'] ?? null,
                    'company' => $clientData['company'],
                    'industry' => $clientData['industry'],
                    'status' => $clientData['status'] ?? 'active',
                    'am' => $clientData['am'] ?? 'Karla Reyes',
                    'contract' => $clientData['contract'] ?? null,
                    'renewal' => $clientData['renewal'] ?? null,
                    'rate' => $clientData['rate'] ?? null,
                    'revenue_q' => $clientData['revenue_q'] ?? null,
                    'tenure' => $clientData['tenure'] ?? null,
                    'next_event' => $clientData['next_event'] ?? null,
                    'card_blurb' => $clientData['card_blurb'] ?? null,
                    'card_tag' => $clientData['card_tag'] ?? null,
                    'card_icon' => $clientData['card_icon'] ?? 'building',
                    'sites' => $clientData['sites'] ?? [],
                    'contact_person' => $clientData['contact_person'],
                    'designation' => $clientData['designation'],
                    'mobile' => $clientData['mobile'],
                    'password' => Hash::make($clientData['password']),
                    'agreed' => true,
                ]
            );
        }
    }
}
