<?php

namespace Database\Seeders;

use App\Models\Applicant;
use App\Models\Deployment;
use Illuminate\Database\Seeder;

class DeploymentSeeder extends Seeder
{
    public function run(): void
    {
        $seeds = [
            [
                'deployment_ref' => 'DEP-001',
                'employee_name' => 'Andrea Molina',
                'client_name' => 'Seda Vertis North',
                'job_order_ref' => 'JO-015',
                'position_title' => 'Front Desk Associate',
                'site_facility' => 'Vertis North, Astra cor. Lux Drive, QC',
                'site_supervisor' => 'Cecille Lim (Hotel GM)',
                'site_supervisor_contact' => '+63 917 555 0192',
                'shift_schedule' => 'Morning Shift (06:00 - 15:00)',
                'start_date' => 'Jul 03, 2026',
                'end_date' => 'Oct 03, 2026',
                'stage' => 'on_site',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'HealthHub Diagnostics QC',
                    'fitToWork' => 'Class A - Fit for Duty',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '34-8901234-5',
                    'philhealth' => '12-050678901-2',
                    'pagibig' => '1210-9876-5432',
                    'tin' => '345-678-901-000',
                    'contractSignedDate' => 'Jul 02, 2026',
                    'ppeGear' => 'Uniform Shirt (M), ID Badge, Safety Shoes (38)',
                    'bankEndorsement' => 'BDO Payroll Endorsement Ref #BDO-2026-089',
                ],
                'history' => [
                    ['date' => 'Jul 01, 2026', 'event' => 'Candidate Assigned', 'note' => 'Hired via Recruitment & Selection for JO-015.'],
                    ['date' => 'Jul 02, 2026', 'event' => 'Pre-Deployment Cleared', 'note' => 'All 6/6 mandatory compliance requirements verified.'],
                    ['date' => 'Jul 03, 2026', 'event' => 'Dispatched & Confirmed On-Site', 'note' => 'Reported to Hotel GM Cecille Lim; active deployment started.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-002',
                'employee_name' => 'Jomar Villagracia',
                'client_name' => 'ABC Logistics',
                'job_order_ref' => 'JO-001',
                'position_title' => 'Warehouse Associate',
                'site_facility' => 'Valenzuela Logistics Hub, NCR',
                'site_supervisor' => 'Mario Santos (Operations Mgr)',
                'site_supervisor_contact' => '+63 918 444 7890',
                'shift_schedule' => 'Night Shift (22:00 - 07:00)',
                'start_date' => 'Jul 03, 2026',
                'end_date' => 'Jan 03, 2027',
                'stage' => 'on_site',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'Hi-Precision Diagnostics Valenzuela',
                    'fitToWork' => 'Class A - Heavy Duty Cleared',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '09-1234567-8',
                    'philhealth' => '04-123456789-0',
                    'pagibig' => '1210-4455-6677',
                    'tin' => '234-567-890-000',
                    'contractSignedDate' => 'Jul 02, 2026',
                    'ppeGear' => 'High-Vis Vest, Steel Toe Shoes (43), Hard Hat',
                    'bankEndorsement' => 'BPI Payroll Endorsement Ref #BPI-2026-112',
                ],
                'history' => [
                    ['date' => 'Jul 01, 2026', 'event' => 'Assigned', 'note' => 'Selected for ABC Logistics warehouse operations.'],
                    ['date' => 'Jul 03, 2026', 'event' => 'On-Site Deployment', 'note' => 'Night shift staging and inventory handler.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-003',
                'employee_name' => 'Danilo Ferrer',
                'client_name' => 'ABC Logistics',
                'job_order_ref' => 'JO-002',
                'position_title' => 'Forklift Operator',
                'site_facility' => 'Valenzuela Logistics Hub, NCR',
                'site_supervisor' => 'Mario Santos (Operations Mgr)',
                'site_supervisor_contact' => '+63 918 444 7890',
                'shift_schedule' => 'Day Shift (08:00 - 17:00)',
                'start_date' => 'Jul 05, 2026',
                'end_date' => 'Oct 05, 2026',
                'stage' => 'on_site',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'HealthHub Diagnostics QC',
                    'fitToWork' => 'Class A - Heavy Equipment Cleared',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '03-9876543-2',
                    'philhealth' => '08-765432109-8',
                    'pagibig' => '1210-9988-7766',
                    'tin' => '123-456-789-000',
                    'contractSignedDate' => 'Jul 04, 2026',
                    'ppeGear' => 'High-Vis Vest, Safety Shoes (42), Gloves, Ear Protection',
                    'bankEndorsement' => 'BDO Payroll Endorsement Ref #BDO-2026-104',
                ],
                'history' => [
                    ['date' => 'Jul 04, 2026', 'event' => 'TESDA Heavy Equipment Verified', 'note' => 'NC II Certificate verified.'],
                    ['date' => 'Jul 05, 2026', 'event' => 'On-Site Deployment', 'note' => 'Active forklift operations.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-004',
                'employee_name' => 'Patricia Gomez',
                'client_name' => 'Vikings Luxury Buffet',
                'job_order_ref' => 'JO-003',
                'position_title' => 'Kitchen Staff / Food Prep',
                'site_facility' => 'SM Mall of Asia, Seaside Blvd, Pasay City',
                'site_supervisor' => 'Marco Santos (Executive Chef)',
                'site_supervisor_contact' => '+63 917 222 3456',
                'shift_schedule' => 'Mid Shift (11:00 - 20:00)',
                'start_date' => 'Jul 10, 2026',
                'end_date' => 'Oct 10, 2026',
                'stage' => 'on_site',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'St. Martin Clinic Pasay',
                    'fitToWork' => 'Food Handler Clearance & Fit to Work',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '04-5566778-9',
                    'philhealth' => '11-334455667-8',
                    'pagibig' => '1210-3322-1100',
                    'tin' => '456-789-012-000',
                    'contractSignedDate' => 'Jul 09, 2026',
                    'ppeGear' => 'Chef Apron, Hair Net, Non-Slip Kitchen Shoes (37)',
                    'bankEndorsement' => 'UnionBank Payroll Ref #UB-2026-045',
                ],
                'history' => [
                    ['date' => 'Jul 09, 2026', 'event' => 'Sanitation Clearance Verified', 'note' => 'Food handler medical certificate cleared.'],
                    ['date' => 'Jul 10, 2026', 'event' => 'Active Deployment', 'note' => 'Kitchen prep and dining support.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-005',
                'employee_name' => 'Joyce Manalastas',
                'client_name' => 'City Garden Hotel',
                'job_order_ref' => 'JO-004',
                'position_title' => 'Housekeeping Attendant',
                'site_facility' => 'P. Burgos cor. Makati Ave, Makati City',
                'site_supervisor' => 'Dennis Ocampo (Hotel Manager)',
                'site_supervisor_contact' => '+63 919 888 1234',
                'shift_schedule' => 'Regular Shift (07:00 - 16:00)',
                'start_date' => 'Jul 26, 2026',
                'end_date' => 'Jan 26, 2027',
                'stage' => 'dispatched',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'Makati Medical Center OPD',
                    'fitToWork' => 'Class A - Fit for Duty',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '07-3344112-3',
                    'philhealth' => '09-223344556-7',
                    'pagibig' => '1210-5544-3322',
                    'tin' => '567-890-123-000',
                    'contractSignedDate' => 'Jul 22, 2026',
                    'ppeGear' => 'Housekeeping Uniform, Rubber Gloves, Service Shoes (38)',
                    'bankEndorsement' => 'BDO Payroll Endorsement Ref #BDO-2026-198',
                ],
                'history' => [
                    ['date' => 'Jul 22, 2026', 'event' => 'Pre-Deployment Cleared', 'note' => 'All items 6/6 verified.'],
                    ['date' => 'Jul 24, 2026', 'event' => 'Deployment Pass Issued', 'note' => 'Dispatched to City Garden Hotel Makati.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-006',
                'employee_name' => 'Nikki Fernandez',
                'client_name' => 'Seda Vertis North',
                'job_order_ref' => 'JO-015',
                'position_title' => 'Front Desk Associate',
                'site_facility' => 'Vertis North, Astra cor. Lux Drive, QC',
                'site_supervisor' => 'Cecille Lim (Hotel GM)',
                'site_supervisor_contact' => '+63 917 555 0192',
                'shift_schedule' => 'Rotating Shift',
                'start_date' => 'Jul 28, 2026',
                'end_date' => 'Oct 28, 2026',
                'stage' => 'pre_deployment',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => false,
                    'clientOrientation' => false,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'HealthHub Diagnostics QC',
                    'fitToWork' => 'Class A - Fit for Duty',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '05-9988776-5',
                    'philhealth' => '10-998877665-4',
                    'pagibig' => '1210-7788-9900',
                    'tin' => '678-901-234-000',
                    'contractSignedDate' => 'Jul 24, 2026',
                    'ppeGear' => 'Uniform Blazer (Pending Size S fitting)',
                    'bankEndorsement' => 'BDO Payroll Endorsement Ref #BDO-2026-211',
                ],
                'history' => [
                    ['date' => 'Jul 23, 2026', 'event' => 'Assigned', 'note' => 'Selected for Front Desk position.'],
                    ['date' => 'Jul 24, 2026', 'event' => 'Compliance Verification', 'note' => 'PPE issuance and orientation pending.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-007',
                'employee_name' => 'Ben Alvarez',
                'client_name' => 'Vikings Luxury Buffet',
                'job_order_ref' => 'JO-003',
                'position_title' => 'Dining Service Associate',
                'site_facility' => 'SM Mall of Asia, Seaside Blvd, Pasay City',
                'site_supervisor' => 'Marco Santos (Executive Chef)',
                'site_supervisor_contact' => '+63 917 222 3456',
                'shift_schedule' => 'Evening Shift (15:00 - 00:00)',
                'start_date' => 'Jul 30, 2026',
                'end_date' => 'Jul 30, 2027',
                'stage' => 'assigned',
                'compliance_checklist' => [
                    'medicalClearance' => false,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => false,
                    'ppeIssued' => false,
                    'clientOrientation' => false,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'Pending Clinic Appointment',
                    'fitToWork' => 'Pending Medical Result',
                    'drugTestResult' => 'Pending Drug Test',
                    'sss' => '02-1122334-4',
                    'philhealth' => '03-556677889-0',
                    'pagibig' => '1210-1122-3344',
                    'tin' => '789-012-345-000',
                    'contractSignedDate' => 'Pending Execution',
                    'ppeGear' => 'Not yet issued',
                    'bankEndorsement' => 'Pending Account Opening',
                ],
                'history' => [
                    ['date' => 'Jul 24, 2026', 'event' => 'Assigned from Pool', 'note' => 'Pending pre-employment medical and fit-to-work clearance.'],
                ],
            ],
            [
                'deployment_ref' => 'DEP-008',
                'employee_name' => 'Rodel Panganiban',
                'client_name' => 'Y2 Hotel Residence',
                'job_order_ref' => 'JO-007',
                'position_title' => 'Maintenance Technician',
                'site_facility' => 'Santiago cor. Valdez St, Makati City',
                'site_supervisor' => 'Gina Alcantara (Head of Operations)',
                'site_supervisor_contact' => '+63 922 555 9012',
                'shift_schedule' => 'Morning Shift (06:00 - 15:00)',
                'start_date' => 'Jun 22, 2026',
                'end_date' => 'Jul 22, 2026',
                'stage' => 'completed',
                'compliance_checklist' => [
                    'medicalClearance' => true,
                    'nbiClearance' => true,
                    'govtIds' => true,
                    'signedContract' => true,
                    'ppeIssued' => true,
                    'clientOrientation' => true,
                ],
                'pre_employment_snapshot' => [
                    'medicalClinic' => 'Makati Medical Center OPD',
                    'fitToWork' => 'Class A - Maintenance & Technical Fit',
                    'drugTestResult' => 'Negative (10-Panel)',
                    'sss' => '01-4455667-8',
                    'philhealth' => '06-990011223-4',
                    'pagibig' => '1210-6677-8899',
                    'tin' => '890-123-456-000',
                    'contractSignedDate' => 'Jun 20, 2026',
                    'ppeGear' => 'Safety Boots (44), Tool Vest, Hard Hat, Insulated Gloves',
                    'bankEndorsement' => 'BDO Payroll Endorsement Ref #BDO-2026-077',
                ],
                'history' => [
                    ['date' => 'Jun 22, 2026', 'event' => 'Deployed On-Site', 'note' => 'Maintenance contract started.'],
                    ['date' => 'Jul 22, 2026', 'event' => 'Deployment Concluded', 'note' => 'Completed 1-month deployment period smoothly.'],
                ],
            ],
        ];

        foreach ($seeds as $data) {
            Deployment::updateOrCreate(
                ['deployment_ref' => $data['deployment_ref']],
                $data
            );
        }
    }
}
