<?php

namespace Database\Seeders;

use App\Models\ClientAccount;
use App\Models\JobOrder;
use Illuminate\Database\Seeder;

class JobOrderSeeder extends Seeder
{
    public function run(): void
    {
        // Lookup client IDs by company name
        $clientMap = ClientAccount::pluck('id', 'company')->toArray();

        $jobs = [
            // ── ABC Logistics ──
            [
                'id' => 'jo1',
                'ref' => 'JO-001',
                'dep_ref' => 'JO-001',
                'client' => 'ABC Logistics',
                'client_account_id' => $clientMap['ABC Logistics'] ?? 1,
                'category' => 'Warehousing & Logistics',
                'title' => 'Warehouse Associate',
                'location' => 'Valenzuela City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱610/day',
                'deadline' => 'Jul 28, 2026',
                'filled' => 12,
                'total' => 15,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'ABC Logistics is looking for Warehouse Associates to support inbound and outbound operations at their Valenzuela distribution center. The role involves receiving, sorting, and staging goods, operating manual pallet jacks, and maintaining accurate inventory counts during shift handovers.',
                'requirements' => json_encode([
                    'At least high school graduate; college level an advantage',
                    '6 months of warehouse or logistics experience preferred',
                    'Able to lift up to 25kg and stand for extended periods',
                    'Willing to work rotating shifts including weekends',
                    'No derogatory record; willing to undergo background check',
                ]),
                'tags' => ['Warehousing', 'Entry-level', 'Shifting Schedule', 'On-site'],
                'applicants' => [
                    ['name' => 'Andrea Molina', 'score' => 92, 'status' => 'hired', 'applied' => 'Jul 01, 2026'],
                    ['name' => 'Jomar Villagracia', 'score' => 89, 'status' => 'hired', 'applied' => 'Jul 01, 2026'],
                    ['name' => 'Rhea Castillo', 'score' => 88, 'status' => 'hired', 'applied' => 'Jul 02, 2026'],
                    ['name' => 'Bryan Aquino', 'score' => 87, 'status' => 'hired', 'applied' => 'Jul 02, 2026'],
                    ['name' => 'Cristina Del Rosario', 'score' => 86, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                    ['name' => 'Edgar Nolasco', 'score' => 85, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                    ['name' => 'Fe Marasigan', 'score' => 85, 'status' => 'hired', 'applied' => 'Jul 04, 2026'],
                    ['name' => 'Gerald Panganiban', 'score' => 84, 'status' => 'hired', 'applied' => 'Jul 04, 2026'],
                    ['name' => 'Hazel Trinidad', 'score' => 83, 'status' => 'hired', 'applied' => 'Jul 05, 2026'],
                    ['name' => 'Ian Buenaventura', 'score' => 82, 'status' => 'hired', 'applied' => 'Jul 06, 2026'],
                    ['name' => 'Jenny Escobar', 'score' => 81, 'status' => 'hired', 'applied' => 'Jul 07, 2026'],
                    ['name' => 'Kevin Salvador', 'score' => 80, 'status' => 'hired', 'applied' => 'Jul 08, 2026'],
                    ['name' => 'Michael Tan', 'score' => 78, 'status' => 'interview', 'applied' => 'Jul 12, 2026'],
                    ['name' => 'Carlo Dizon', 'score' => 70, 'status' => 'screening', 'applied' => 'Jul 14, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo2',
                'ref' => 'JO-002',
                'dep_ref' => 'JO-002',
                'client' => 'ABC Logistics',
                'client_account_id' => $clientMap['ABC Logistics'] ?? 1,
                'category' => 'Warehousing & Logistics',
                'title' => 'Forklift Operator',
                'location' => 'Valenzuela City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱650/day',
                'deadline' => 'Aug 1, 2026',
                'filled' => 3,
                'total' => 5,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'high',
                'description' => 'ABC Logistics needs licensed Forklift Operators to move palletized goods within the warehouse and load/unload delivery trucks safely and efficiently.',
                'requirements' => json_encode([
                    'Valid forklift operator certification/license',
                    'At least 1 year of forklift operating experience',
                    'Good understanding of warehouse safety protocols',
                    'Willing to work rotating shifts',
                ]),
                'tags' => ['Warehousing', 'Licensed', 'Heavy Equipment', 'On-site'],
                'applicants' => [
                    ['name' => 'Danilo Ferrer', 'score' => 90, 'status' => 'hired', 'applied' => 'Jul 02, 2026'],
                    ['name' => 'Ramil Cabrera', 'score' => 87, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                    ['name' => 'Wilfredo Santos', 'score' => 85, 'status' => 'hired', 'applied' => 'Jul 04, 2026'],
                    ['name' => 'Vince Ocampo', 'score' => 72, 'status' => 'screening', 'applied' => 'Jul 11, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo3',
                'ref' => 'JO-003',
                'dep_ref' => 'JO-003',
                'client' => 'ABC Logistics',
                'client_account_id' => $clientMap['ABC Logistics'] ?? 1,
                'category' => 'Warehousing & Logistics',
                'title' => 'Inventory Clerk',
                'location' => 'Valenzuela City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱18,000/mo',
                'deadline' => 'Jul 10, 2026',
                'filled' => 4,
                'total' => 4,
                'status' => 'filled',
                'stage' => 'completed',
                'priority' => 'normal',
                'description' => 'Inventory Clerks manage stock levels, reconcile physical counts with WMS data, and generate daily discrepancy reports for the operations manager.',
                'requirements' => json_encode([
                    'Graduate of any business or IT course',
                    'Proficient in Excel and basic WMS software',
                    'High attention to detail and numerical accuracy',
                    'At least 1 year experience in inventory management',
                ]),
                'tags' => ['Warehousing', 'Inventory', 'Completed'],
                'applicants' => [
                    ['name' => 'Marivic Santos', 'score' => 94, 'status' => 'hired', 'applied' => 'Jun 25, 2026'],
                    ['name' => 'Allan Bautista', 'score' => 91, 'status' => 'hired', 'applied' => 'Jun 26, 2026'],
                    ['name' => 'Joy Ramirez', 'score' => 88, 'status' => 'hired', 'applied' => 'Jun 27, 2026'],
                    ['name' => 'Nestor Villamor', 'score' => 84, 'status' => 'hired', 'applied' => 'Jun 28, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo4',
                'ref' => 'JO-004',
                'dep_ref' => 'JO-004',
                'client' => 'ABC Logistics',
                'client_account_id' => $clientMap['ABC Logistics'] ?? 1,
                'category' => 'Warehousing & Logistics',
                'title' => 'Delivery Driver',
                'location' => 'Valenzuela City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱700/day',
                'deadline' => 'Aug 10, 2026',
                'filled' => 3,
                'total' => 6,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'medium',
                'description' => 'Delivery Drivers operate 4-wheel and 6-wheel closed vans to transport goods from the Valenzuela hub to retail clients across Metro Manila.',
                'requirements' => json_encode([
                    "Professional Driver's License (Restriction Code 2, 3)",
                    'At least 2 years commercial driving experience',
                    'Familiar with Metro Manila delivery routes and road regulations',
                    'Clean driving record and no derogatory findings',
                ]),
                'tags' => ['Logistics', 'Driving', 'On-site'],
                'applicants' => [
                    ['name' => 'Ronald Espino', 'score' => 89, 'status' => 'hired', 'applied' => 'Jul 05, 2026'],
                    ['name' => 'Freddie Manalo', 'score' => 86, 'status' => 'hired', 'applied' => 'Jul 06, 2026'],
                    ['name' => 'Bea Concepcion', 'score' => 82, 'status' => 'hired', 'applied' => 'Jul 07, 2026'],
                ],
                'source' => 'internal',
            ],

            // ── Northline BPO ──
            [
                'id' => 'jo5',
                'ref' => 'JO-005',
                'dep_ref' => 'JO-005',
                'client' => 'Northline BPO',
                'client_account_id' => $clientMap['Northline BPO'] ?? 2,
                'category' => 'Customer Service (BPO)',
                'title' => 'Customer Service Representative',
                'location' => 'Ortigas Center, Pasig City',
                'type' => 'Full-time · Regular',
                'rate' => '₱22,000/mo + allowances',
                'deadline' => 'Jul 25, 2026',
                'filled' => 7,
                'total' => 20,
                'status' => 'urgent',
                'stage' => 'in_progress',
                'priority' => 'urgent',
                'description' => 'Northline BPO is ramping up a 20-seat team for a premier US retail client. CSRs will handle inbound voice and chat inquiries regarding orders, tracking, refunds, and product questions during US business hours (graveyard shift).',
                'requirements' => json_encode([
                    'At least 2 years of college completed',
                    'Excellent verbal and written English communication skills',
                    'Typing speed of at least 35 wpm with 90% accuracy',
                    'Willing to work night shifts, weekends, and holidays',
                    'Previous BPO customer service experience is an advantage',
                ]),
                'tags' => ['BPO', 'Voice/Non-Voice', 'Night Shift', 'Urgent'],
                'applicants' => [
                    ['name' => 'Bianca Reyes', 'score' => 93, 'status' => 'hired', 'applied' => 'Jul 01, 2026'],
                    ['name' => 'Trisha Navarro', 'score' => 87, 'status' => 'hired', 'applied' => 'Jul 02, 2026'],
                    ['name' => 'Owen Legaspi', 'score' => 85, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                    ['name' => 'Karen Alonzo', 'score' => 83, 'status' => 'hired', 'applied' => 'Jul 04, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo6',
                'ref' => 'JO-006',
                'dep_ref' => 'JO-006',
                'client' => 'Northline BPO',
                'client_account_id' => $clientMap['Northline BPO'] ?? 2,
                'category' => 'Customer Service (BPO)',
                'title' => 'Technical Support Agent',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱24,000/mo + allowances',
                'deadline' => 'Jul 30, 2026',
                'filled' => 8,
                'total' => 10,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Technical Support Agents will assist customers with internet and device troubleshooting for a telecom account, guiding callers through step-by-step resolutions and escalating unresolved technical issues.',
                'requirements' => json_encode([
                    'At least 2 years college; IT/technical background a plus',
                    'Strong English communication and problem-solving skills',
                    'Basic understanding of networking/device troubleshooting',
                    'Willing to work night shift on-site',
                ]),
                'tags' => ['BPO', 'Technical', 'Night Shift'],
                'applicants' => [
                    ['name' => 'Aldrin Cruz', 'score' => 86, 'status' => 'hired', 'applied' => 'Jul 02, 2026'],
                    ['name' => 'Shane Villareal', 'score' => 83, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                    ['name' => 'Ferdinand Yu', 'score' => 82, 'status' => 'hired', 'applied' => 'Jul 03, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo7',
                'ref' => 'JO-007',
                'dep_ref' => 'JO-007',
                'client' => 'Northline BPO',
                'client_account_id' => $clientMap['Northline BPO'] ?? 2,
                'category' => 'Customer Service (BPO)',
                'title' => 'Sales Development Representative',
                'location' => 'Ortigas Center, Pasig City',
                'type' => 'Full-time · Regular',
                'rate' => '₱25,000/mo + commissions',
                'deadline' => 'Aug 1, 2026',
                'filled' => 6,
                'total' => 15,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'medium',
                'description' => "SDRs will handle outbound and inbound sales calls for a US retail account, qualifying leads and booking appointments for the client's account executives.",
                'requirements' => json_encode([
                    'At least 2 years college; sales experience a plus',
                    'Strong spoken English and persuasive communication',
                    'Comfortable with cold calling and CRM tools',
                    'Willing to work night shift on-site',
                ]),
                'tags' => ['BPO', 'Sales', 'Night Shift'],
                'applicants' => [
                    ['name' => 'Precious Dela Cruz', 'score' => 89, 'status' => 'hired', 'applied' => 'Jul 10, 2026'],
                    ['name' => 'Julius Bermudez', 'score' => 85, 'status' => 'hired', 'applied' => 'Jul 11, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo8',
                'ref' => 'JO-008',
                'dep_ref' => 'JO-008',
                'client' => 'Northline BPO',
                'client_account_id' => $clientMap['Northline BPO'] ?? 2,
                'category' => 'Customer Service (BPO)',
                'title' => 'Team Leader - Customer Experience',
                'location' => 'Ortigas Center, Pasig City',
                'type' => 'Full-time · Regular',
                'rate' => '₱32,000/mo',
                'deadline' => 'Aug 20, 2026',
                'filled' => 1,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'high',
                'description' => 'Team Leaders will supervise a pod of 15-18 CSR agents, monitor quality and attendance, and coach agents to meet client KPIs.',
                'requirements' => json_encode([
                    'At least 2 years of BPO team leadership experience',
                    'Proven track record hitting quality/CSAT targets',
                    'Strong coaching and people-management skills',
                    'Willing to work night shift on-site',
                ]),
                'tags' => ['BPO', 'Leadership', 'Night Shift'],
                'applicants' => [
                    ['name' => 'Cherry Anne Molina', 'score' => 91, 'status' => 'hired', 'applied' => 'Jul 12, 2026'],
                ],
                'source' => 'internal',
            ],

            // ── Delta Manufacturing ──
            [
                'id' => 'jo9',
                'ref' => 'JO-009',
                'dep_ref' => 'JO-009',
                'client' => 'Delta Manufacturing',
                'client_account_id' => $clientMap['Delta Manufacturing'] ?? 3,
                'category' => 'Manufacturing',
                'title' => 'Machine Operator',
                'location' => 'Cabuyao, Laguna',
                'type' => 'Full-time · Contractual',
                'rate' => '₱580/day',
                'deadline' => 'Jul 22, 2026',
                'filled' => 1,
                'total' => 10,
                'status' => 'urgent',
                'stage' => 'in_progress',
                'priority' => 'urgent',
                'description' => 'Delta Manufacturing requires Machine Operators for its plastics injection molding line. Operators will run and monitor molding machines, perform basic quality checks on finished parts, and report equipment issues to the shift supervisor.',
                'requirements' => json_encode([
                    'Vocational/technical course graduate preferred',
                    'Experience operating industrial machinery is a plus',
                    'Willing to work 8-hour rotating shifts, including graveyard',
                    'Keen attention to detail for quality inspection',
                    'Physically fit; able to stand for long periods',
                ]),
                'tags' => ['Manufacturing', 'Urgent', 'Rotating Shift', 'On-site'],
                'applicants' => [
                    ['name' => 'Rodel Manalastas', 'score' => 79, 'status' => 'hired', 'applied' => 'Jul 05, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo10',
                'ref' => 'JO-010',
                'dep_ref' => 'JO-010',
                'client' => 'Delta Manufacturing',
                'client_account_id' => $clientMap['Delta Manufacturing'] ?? 3,
                'category' => 'Manufacturing',
                'title' => 'Quality Control Inspector',
                'location' => 'Cabuyao, Laguna',
                'type' => 'Full-time · Contractual',
                'rate' => '₱640/day',
                'deadline' => 'Aug 5, 2026',
                'filled' => 2,
                'total' => 4,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'QC Inspectors will inspect molded components against engineering specs, conduct drop tests and dimensional measurements, and log non-conformance reports.',
                'requirements' => json_encode([
                    'Graduate of any technical/engineering course',
                    'At least 1 year QC inspection experience in a manufacturing plant',
                    'Knowledge of calipers, micrometers, and basic QA tools',
                    'Can work shifting schedules',
                ]),
                'tags' => ['Manufacturing', 'Quality Control', 'Technical'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo11',
                'ref' => 'JO-011',
                'dep_ref' => 'JO-011',
                'client' => 'Delta Manufacturing',
                'client_account_id' => $clientMap['Delta Manufacturing'] ?? 3,
                'category' => 'Manufacturing',
                'title' => 'Production Line Supervisor',
                'location' => 'Cabuyao, Laguna',
                'type' => 'Full-time · Regular',
                'rate' => '₱28,000/mo',
                'deadline' => 'Aug 15, 2026',
                'filled' => 1,
                'total' => 2,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'high',
                'description' => 'Supervises a production shift of 25-30 line workers and machine operators, ensuring output quotas, safety compliance, and shift reporting are maintained.',
                'requirements' => json_encode([
                    "Bachelor's degree in Industrial Engineering or related field",
                    'At least 2 years supervisory experience in manufacturing',
                    'Strong leadership, troubleshooting, and reporting skills',
                    'Willing to work shifting schedule in Cabuyao, Laguna',
                ]),
                'tags' => ['Manufacturing', 'Leadership', 'Industrial'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo12',
                'ref' => 'JO-012',
                'dep_ref' => 'JO-012',
                'client' => 'Delta Manufacturing',
                'client_account_id' => $clientMap['Delta Manufacturing'] ?? 3,
                'category' => 'Manufacturing',
                'title' => 'Packaging Associate',
                'location' => 'Cabuyao, Laguna',
                'type' => 'Full-time · Contractual',
                'rate' => '₱550/day',
                'deadline' => 'Aug 8, 2026',
                'filled' => 3,
                'total' => 8,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'normal',
                'description' => 'Packages finished plastic components into cartons, applies shipping labels, and stacks pallets for warehouse transfer.',
                'requirements' => json_encode([
                    'High school graduate or equivalent',
                    'Prior packing or assembly line experience preferred',
                    'Fast and accurate hand-eye coordination',
                    'Physically fit',
                ]),
                'tags' => ['Manufacturing', 'Packaging', 'Entry-level'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── Coastal Retail Group ──
            [
                'id' => 'jo13',
                'ref' => 'JO-013',
                'dep_ref' => 'JO-013',
                'client' => 'Coastal Retail Group',
                'client_account_id' => $clientMap['Coastal Retail Group'] ?? 4,
                'category' => 'Retail & Store Operations',
                'title' => 'Admin Assistant',
                'location' => 'Pasay City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱19,000/mo',
                'deadline' => 'Jul 29, 2026',
                'filled' => 2,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Admin Assistants handle store supply orders, staff scheduling records, vendor invoices, and general administrative coordination for the store manager.',
                'requirements' => json_encode([
                    'Graduate of any 4-year business or administrative course',
                    'Proficient in MS Word, Excel, and Outlook',
                    'Good interpersonal and phone communication skills',
                    'Organized and detail-oriented',
                ]),
                'tags' => ['Retail', 'Administrative', 'Office'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo14',
                'ref' => 'JO-014',
                'dep_ref' => 'JO-014',
                'client' => 'Coastal Retail Group',
                'client_account_id' => $clientMap['Coastal Retail Group'] ?? 4,
                'category' => 'Retail & Store Operations',
                'title' => 'Sales Associate',
                'location' => 'Pasay City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱570/day + commissions',
                'deadline' => 'Aug 5, 2026',
                'filled' => 8,
                'total' => 12,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'medium',
                'description' => 'Sales Associates welcome store customers, demonstrate products, answer inquiries, and maintain visual merchandising standards on the sales floor.',
                'requirements' => json_encode([
                    'At least High School graduate / Senior High School',
                    'Pleasing personality with excellent customer service skills',
                    'Prior retail sales experience is an advantage',
                    'Willing to work mall hours, weekends, and holidays',
                ]),
                'tags' => ['Retail', 'Sales', 'Customer Facing'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo15',
                'ref' => 'JO-015',
                'dep_ref' => 'JO-015',
                'client' => 'Coastal Retail Group',
                'client_account_id' => $clientMap['Coastal Retail Group'] ?? 4,
                'category' => 'Retail & Store Operations',
                'title' => 'Store Cashier',
                'location' => 'Pasay City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱570/day',
                'deadline' => 'Aug 12, 2026',
                'filled' => 4,
                'total' => 6,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Processes cash, credit card, and e-wallet transactions accurately at POS terminals, handles cash reconciliation, and provides receipts to customers.',
                'requirements' => json_encode([
                    'High school graduate; college level preferred',
                    'Basic math and computer skills; POS experience a plus',
                    'Honest, reliable, and attentive to detail',
                    'Willing to work rotating mall shifts',
                ]),
                'tags' => ['Retail', 'Cashier', 'POS'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo16',
                'ref' => 'JO-016',
                'dep_ref' => 'JO-016',
                'client' => 'Coastal Retail Group',
                'client_account_id' => $clientMap['Coastal Retail Group'] ?? 4,
                'category' => 'Retail & Store Operations',
                'title' => 'Visual Merchandiser',
                'location' => 'Pasay City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱22,000/mo',
                'deadline' => 'Aug 18, 2026',
                'filled' => 1,
                'total' => 2,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Designs and maintains window displays, floor layouts, and promotional signage across 3 mall branches to drive foot traffic and brand appeal.',
                'requirements' => json_encode([
                    'Degree in Fine Arts, Interior Design, Marketing, or related',
                    'At least 1 year visual merchandising experience in retail',
                    'Creative eye for styling, color coordination, and space planning',
                    'Willing to travel between Metro Manila store branches',
                ]),
                'tags' => ['Retail', 'Visual Merchandising', 'Creative'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── Sunrise Hospitality Group ──
            [
                'id' => 'jo17',
                'ref' => 'JO-017',
                'dep_ref' => 'JO-017',
                'client' => 'Sunrise Hospitality Group',
                'client_account_id' => $clientMap['Sunrise Hospitality Group'] ?? 8,
                'category' => 'Hospitality & Front Desk',
                'title' => 'Front Desk Associate',
                'location' => 'Boracay, Aklan',
                'type' => 'Full-time · Contractual',
                'rate' => '₱18,000/mo + lodging',
                'deadline' => 'Aug 15, 2026',
                'filled' => 7,
                'total' => 8,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Front Desk Associates manage guest check-ins/check-outs, room reservations, concierge requests, and guest feedback at the resort.',
                'requirements' => json_encode([
                    'Graduate of Hospitality / Tourism Management',
                    'Pleasing personality and fluent English; additional language a plus',
                    'Knowledge of Opera or PMS software is an advantage',
                    'Willing to relocate to Boracay (free staff accommodation)',
                ]),
                'tags' => ['Hospitality', 'Front Desk', 'Resort'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo18',
                'ref' => 'JO-018',
                'dep_ref' => 'JO-018',
                'client' => 'Sunrise Hospitality Group',
                'client_account_id' => $clientMap['Sunrise Hospitality Group'] ?? 8,
                'category' => 'Hospitality & Front Desk',
                'title' => 'Housekeeping Staff',
                'location' => 'Boracay, Aklan',
                'type' => 'Full-time · Contractual',
                'rate' => '₱560/day + lodging',
                'deadline' => 'Aug 25, 2026',
                'filled' => 6,
                'total' => 8,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'normal',
                'description' => 'Maintains cleanliness and sanitation of resort guest rooms, villas, and common areas to 5-star resort standards.',
                'requirements' => json_encode([
                    'High school graduate; TESDA Housekeeping NC II a plus',
                    'Attention to detail and physical stamina',
                    'Trustworthy with guest belongings',
                    'Staff housing provided',
                ]),
                'tags' => ['Hospitality', 'Housekeeping', 'Resort'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo19',
                'ref' => 'JO-019',
                'dep_ref' => 'JO-019',
                'client' => 'Sunrise Hospitality Group',
                'client_account_id' => $clientMap['Sunrise Hospitality Group'] ?? 8,
                'category' => 'Food & Beverage (F&B / Cook)',
                'title' => 'Food & Beverage Server',
                'location' => 'Boracay, Aklan',
                'type' => 'Full-time · Contractual',
                'rate' => '₱580/day + tips',
                'deadline' => 'Aug 20, 2026',
                'filled' => 10,
                'total' => 15,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Servers and bartenders for beachfront dining and resort banquet events.',
                'requirements' => json_encode([
                    'TESDA Food and Beverage NC II preferred',
                    'At least 6 months experience in hotel or restaurant service',
                    'Warm, hospitable, and energetic demeanor',
                    'Free lodging provided',
                ]),
                'tags' => ['Hospitality', 'F&B', 'Resort'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo20',
                'ref' => 'JO-020',
                'dep_ref' => 'JO-020',
                'client' => 'Sunrise Hospitality Group',
                'client_account_id' => $clientMap['Sunrise Hospitality Group'] ?? 8,
                'category' => 'Hospitality & Front Desk',
                'title' => 'Maintenance Technician',
                'location' => 'Boracay, Aklan',
                'type' => 'Full-time · Regular',
                'rate' => '₱22,000/mo + lodging',
                'deadline' => 'Aug 30, 2026',
                'filled' => 3,
                'total' => 4,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'Conducts preventive maintenance, plumbing, electrical, and HVAC repairs for resort villas and recreational amenities.',
                'requirements' => json_encode([
                    'TESDA Electrical / HVAC / Plumbing NC II',
                    'At least 2 years hotel or resort facilities maintenance experience',
                    'Staff lodging provided',
                ]),
                'tags' => ['Hospitality', 'Facilities', 'Maintenance'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── Prime Realty Corp ──
            [
                'id' => 'jo21',
                'ref' => 'JO-021',
                'dep_ref' => 'JO-021',
                'client' => 'Prime Realty Corp',
                'client_account_id' => $clientMap['Prime Realty Corp'] ?? 9,
                'category' => 'Real Estate & Property Management',
                'title' => 'Leasing Consultant',
                'location' => 'Pasig City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱26,000/mo + commissions',
                'deadline' => 'Aug 28, 2026',
                'filled' => 3,
                'total' => 5,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'high',
                'description' => 'Conducts site viewings, prepares leasing proposals, and assists corporate clients with tenancy documentation for commercial office towers.',
                'requirements' => json_encode([
                    "Bachelor's degree in Real Estate Management, Marketing, or Business",
                    'At least 1 year leasing experience in commercial real estate',
                    'Excellent presentation and contract negotiation skills',
                ]),
                'tags' => ['Real Estate', 'Leasing', 'Commercial'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo22',
                'ref' => 'JO-022',
                'dep_ref' => 'JO-022',
                'client' => 'Prime Realty Corp',
                'client_account_id' => $clientMap['Prime Realty Corp'] ?? 9,
                'category' => 'Real Estate & Property Management',
                'title' => 'Property Administrator',
                'location' => 'Taguig City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱24,000/mo',
                'deadline' => 'Sep 05, 2026',
                'filled' => 2,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Manages tenant inquiries, billing notices, gate pass permits, and facility contractor coordination.',
                'requirements' => json_encode([
                    'Graduate of Business Administration or relevant course',
                    'Strong administrative and tenant relations skills',
                    'Proficient in property management software and MS Office',
                ]),
                'tags' => ['Real Estate', 'Property Management', 'Admin'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo23',
                'ref' => 'JO-023',
                'dep_ref' => 'JO-023',
                'client' => 'Prime Realty Corp',
                'client_account_id' => $clientMap['Prime Realty Corp'] ?? 9,
                'category' => 'Real Estate & Property Management',
                'title' => 'Front Desk Officer',
                'location' => 'Pasig City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱620/day',
                'deadline' => 'Sep 10, 2026',
                'filled' => 4,
                'total' => 6,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'medium',
                'description' => 'Manages the main lobby reception, visitor badge issuance, and concierge services for prime office buildings.',
                'requirements' => json_encode([
                    'College level or graduate with pleasing personality',
                    'Excellent verbal communication and professional etiquette',
                    'Experience in corporate concierge or front desk is a plus',
                ]),
                'tags' => ['Real Estate', 'Front Desk', 'Concierge'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo24',
                'ref' => 'JO-024',
                'dep_ref' => 'JO-024',
                'client' => 'Prime Realty Corp',
                'client_account_id' => $clientMap['Prime Realty Corp'] ?? 9,
                'category' => 'Real Estate & Property Management',
                'title' => 'Maintenance Coordinator',
                'location' => 'Taguig City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱23,000/mo',
                'deadline' => 'Sep 12, 2026',
                'filled' => 2,
                'total' => 4,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Coordinates building engineering services, fire safety inspections, and elevator/generator maintenance schedules.',
                'requirements' => json_encode([
                    'Technical diploma or engineering background',
                    'Knowledge of building maintenance and safety regulations',
                ]),
                'tags' => ['Real Estate', 'Facilities', 'Operations'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── Metro Health Diagnostics ──
            [
                'id' => 'jo25',
                'ref' => 'JO-025',
                'dep_ref' => 'JO-025',
                'client' => 'Metro Health Diagnostics',
                'client_account_id' => $clientMap['Metro Health Diagnostics'] ?? 10,
                'category' => 'Healthcare & Diagnostics',
                'title' => 'Medical Technologist',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Regular',
                'rate' => '₱28,000/mo + hazard pay',
                'deadline' => 'Aug 25, 2026',
                'filled' => 5,
                'total' => 8,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'PRC-licensed Medical Technologist to perform clinical laboratory analysis including hematology, clinical chemistry, and serology across branch clinics.',
                'requirements' => json_encode([
                    'BS Medical Technology graduate with valid PRC license',
                    'Proficient in automated clinical analyzers and phlebotomy',
                    'Detail-oriented with strict adherence to DOH laboratory standards',
                ]),
                'tags' => ['Healthcare', 'PRC Licensed', 'Laboratory'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo26',
                'ref' => 'JO-026',
                'dep_ref' => 'JO-026',
                'client' => 'Metro Health Diagnostics',
                'client_account_id' => $clientMap['Metro Health Diagnostics'] ?? 10,
                'category' => 'Healthcare & Diagnostics',
                'title' => 'Radiologic Technologist',
                'location' => 'Ermita, Manila',
                'type' => 'Full-time · Regular',
                'rate' => '₱26,000/mo',
                'deadline' => 'Sep 01, 2026',
                'filled' => 3,
                'total' => 4,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'PRC-licensed RadTech for diagnostic X-ray procedures, imaging calibration, and radiation safety compliance.',
                'requirements' => json_encode([
                    'BS Radiologic Technology graduate with valid PRC license',
                    'At least 1 year clinical radiography experience',
                ]),
                'tags' => ['Healthcare', 'RadTech', 'PRC Licensed'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo27',
                'ref' => 'JO-027',
                'dep_ref' => 'JO-027',
                'client' => 'Metro Health Diagnostics',
                'client_account_id' => $clientMap['Metro Health Diagnostics'] ?? 10,
                'category' => 'Healthcare & Diagnostics',
                'title' => 'Patient Service Representative',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Contractual',
                'rate' => '₱590/day',
                'deadline' => 'Sep 05, 2026',
                'filled' => 6,
                'total' => 8,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'normal',
                'description' => 'Assists patients with diagnostic package inquiries, test queuing, PhilHealth/HMO verification, and test result release.',
                'requirements' => json_encode([
                    'College graduate or Allied Health diploma',
                    'Compassionate customer care and basic HMO approval workflow knowledge',
                ]),
                'tags' => ['Healthcare', 'Patient Care', 'HMO'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo28',
                'ref' => 'JO-028',
                'dep_ref' => 'JO-028',
                'client' => 'Metro Health Diagnostics',
                'client_account_id' => $clientMap['Metro Health Diagnostics'] ?? 10,
                'category' => 'Healthcare & Diagnostics',
                'title' => 'Billing Clerk',
                'location' => 'Ermita, Manila',
                'type' => 'Full-time · Regular',
                'rate' => '₱19,000/mo',
                'deadline' => 'Sep 10, 2026',
                'filled' => 2,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Processes medical billing statements, HMO claims submission, and daily revenue reconciliations.',
                'requirements' => json_encode([
                    'Accounting or business graduate',
                    'Experience in hospital or clinic billing preferred',
                ]),
                'tags' => ['Healthcare', 'Billing', 'Finance'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── GreenFields Agri Export ──
            [
                'id' => 'jo29',
                'ref' => 'JO-029',
                'dep_ref' => 'JO-029',
                'client' => 'GreenFields Agri Export',
                'client_account_id' => $clientMap['GreenFields Agri Export'] ?? 12,
                'category' => 'Agriculture & Export',
                'title' => 'Packing Associate',
                'location' => 'Lipa City, Batangas',
                'type' => 'Full-time · Seasonal',
                'rate' => '₱540/day',
                'deadline' => 'Sep 15, 2026',
                'filled' => 15,
                'total' => 25,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Sorts, weighs, and packs fresh agricultural produce into export-grade temperature-controlled containers.',
                'requirements' => json_encode([
                    'High school graduate with physical fitness certification',
                    'Willing to work in cold storage processing facility',
                ]),
                'tags' => ['Agriculture', 'Cold Chain', 'Export'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo30',
                'ref' => 'JO-030',
                'dep_ref' => 'JO-030',
                'client' => 'GreenFields Agri Export',
                'client_account_id' => $clientMap['GreenFields Agri Export'] ?? 12,
                'category' => 'Agriculture & Export',
                'title' => 'QA Inspector (Agri)',
                'location' => 'Lipa City, Batangas',
                'type' => 'Full-time · Regular',
                'rate' => '₱22,000/mo',
                'deadline' => 'Sep 20, 2026',
                'filled' => 3,
                'total' => 4,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'Inspects fruit and vegetable quality against Bureau of Plant Industry and international export phyto-sanitary standards.',
                'requirements' => json_encode([
                    'BS Agriculture, Food Technology, or related science degree',
                    'Knowledge of GAP (Good Agricultural Practices) and HACCP',
                ]),
                'tags' => ['Agriculture', 'Quality Assurance', 'Export'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo31',
                'ref' => 'JO-031',
                'dep_ref' => 'JO-031',
                'client' => 'GreenFields Agri Export',
                'client_account_id' => $clientMap['GreenFields Agri Export'] ?? 12,
                'category' => 'Agriculture & Export',
                'title' => 'Logistics Coordinator',
                'location' => 'Lipa City, Batangas',
                'type' => 'Full-time · Regular',
                'rate' => '₱23,000/mo',
                'deadline' => 'Sep 25, 2026',
                'filled' => 2,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'normal',
                'description' => 'Coordinates refrigerated container bookings, port customs clearance, and farm-to-dock transport logistics.',
                'requirements' => json_encode([
                    'Logistics or Supply Chain degree',
                    'Experience with cold chain shipping and export documentation',
                ]),
                'tags' => ['Agriculture', 'Logistics', 'Shipping'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo32',
                'ref' => 'JO-032',
                'dep_ref' => 'JO-032',
                'client' => 'GreenFields Agri Export',
                'client_account_id' => $clientMap['GreenFields Agri Export'] ?? 12,
                'category' => 'Agriculture & Export',
                'title' => 'Farm Supervisor',
                'location' => 'Lipa City, Batangas',
                'type' => 'Full-time · Regular',
                'rate' => '₱27,000/mo',
                'deadline' => 'Sep 30, 2026',
                'filled' => 1,
                'total' => 2,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'Supervises contract growers, harvesting crews, and pest management schedules across partner plantations.',
                'requirements' => json_encode([
                    'BS Agriculture graduate with farm management experience',
                ]),
                'tags' => ['Agriculture', 'Supervision', 'Field Ops'],
                'applicants' => [],
                'source' => 'internal',
            ],

            // ── Apex Construction Builders ──
            [
                'id' => 'jo33',
                'ref' => 'JO-033',
                'dep_ref' => 'JO-033',
                'client' => 'Apex Construction Builders',
                'client_account_id' => $clientMap['Apex Construction Builders'] ?? 11,
                'category' => 'Construction & Engineering',
                'title' => 'Construction Laborer',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Project-based',
                'rate' => '₱620/day',
                'deadline' => 'Aug 10, 2026',
                'filled' => 20,
                'total' => 30,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'high',
                'description' => 'Assists skilled trades on high-rise construction with concrete pouring, rebar hauling, and site housekeeping.',
                'requirements' => json_encode([
                    'Physically fit for heavy construction labor',
                    'Completed mandatory DOLE Construction Safety Orientation',
                ]),
                'tags' => ['Construction', 'Labor', 'On-site'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo34',
                'ref' => 'JO-034',
                'dep_ref' => 'JO-034',
                'client' => 'Apex Construction Builders',
                'client_account_id' => $clientMap['Apex Construction Builders'] ?? 11,
                'category' => 'Construction & Engineering',
                'title' => 'Site Engineer Assistant',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Project-based',
                'rate' => '₱26,000/mo',
                'deadline' => 'Aug 15, 2026',
                'filled' => 2,
                'total' => 3,
                'status' => 'open',
                'stage' => 'activated',
                'priority' => 'medium',
                'description' => 'Assists project engineers with daily site logs, material quantity estimates, and contractor milestone inspections.',
                'requirements' => json_encode([
                    'BS Civil Engineering graduate',
                    'Proficient in AutoCAD and reading architectural/structural blueprints',
                ]),
                'tags' => ['Construction', 'Engineering', 'AutoCAD'],
                'applicants' => [],
                'source' => 'internal',
            ],
            [
                'id' => 'jo35',
                'ref' => 'JO-035',
                'dep_ref' => 'JO-035',
                'client' => 'Apex Construction Builders',
                'client_account_id' => $clientMap['Apex Construction Builders'] ?? 11,
                'category' => 'Construction & Engineering',
                'title' => 'Safety Officer 2',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Project-based',
                'rate' => '₱35,000/mo',
                'deadline' => 'Jul 05, 2026',
                'filled' => 4,
                'total' => 4,
                'status' => 'filled',
                'stage' => 'completed',
                'priority' => 'high',
                'description' => 'DOLE-certified SO2 to conduct daily safety briefings, inspect scaffolding, and ensure full compliance with OSH standards on high-rise construction.',
                'requirements' => json_encode([
                    'DOLE BOSH / COSH 40-hour certificate',
                    'At least 2 years safety officer experience in high-rise building',
                    'Strong reporting and incident investigation skills',
                ]),
                'tags' => ['Construction', 'Safety', 'Completed'],
                'applicants' => [
                    ['name' => 'Ramon Estacio', 'score' => 95, 'status' => 'hired', 'applied' => 'Jun 15, 2026'],
                    ['name' => 'Bayani Cruz', 'score' => 92, 'status' => 'hired', 'applied' => 'Jun 16, 2026'],
                    ['name' => 'Edgardo Marasigan', 'score' => 89, 'status' => 'hired', 'applied' => 'Jun 17, 2026'],
                    ['name' => 'Willy Santos', 'score' => 87, 'status' => 'hired', 'applied' => 'Jun 18, 2026'],
                ],
                'source' => 'internal',
            ],
            [
                'id' => 'jo36',
                'ref' => 'JO-036',
                'dep_ref' => 'JO-036',
                'client' => 'Apex Construction Builders',
                'client_account_id' => $clientMap['Apex Construction Builders'] ?? 11,
                'category' => 'Construction & Engineering',
                'title' => 'Tower Crane Operator',
                'location' => 'Quezon City, NCR',
                'type' => 'Full-time · Project-based',
                'rate' => '₱950/day',
                'deadline' => 'Aug 10, 2026',
                'filled' => 1,
                'total' => 2,
                'status' => 'filling',
                'stage' => 'in_progress',
                'priority' => 'urgent',
                'description' => 'TESDA-certified Heavy Equipment Operator for high-capacity tower crane hoisting steel and formworks.',
                'requirements' => json_encode([
                    'TESDA NC II for Heavy Equipment Operation (Tower Crane)',
                    'At least 3 years experience operating tower cranes in high-rise projects',
                    'Physical fitness certification and no acrophobia',
                ]),
                'tags' => ['Construction', 'Heavy Equipment', 'Licensed'],
                'applicants' => [
                    ['name' => 'Engr. Ivan Buenavista', 'score' => 90, 'status' => 'hired', 'applied' => 'Jul 08, 2026'],
                ],
                'source' => 'internal',
            ],
        ];

        JobOrder::truncate();

        foreach ($jobs as $job) {
            JobOrder::create($job);
        }
    }
}
